### ISSUE TITLE
[Button] The private relay icon causes the email field to expand 

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/fx-private-relay#204]
**Affected versions**
* latest Nightly 77.0a1

**Affected platforms**
* Windows 10 x64
* macOS 10.15
* Ubuntu 18.04 x64

**Prerequisites**
* Firefox is opened.
* Have the Private Relay add-on version 1.2.0 installed - https://drive.google.com/file/d/1OqZCFEwHrbUTH0q1dQUJBI43qVBaM3Hw/view.

**Steps to reproduce**
1. Access https://www.facebook.com/pages/create/?ref_type=registration_form.
2. Click on the "Join or Log Into Facebook" button from the upper right side of the page.
3. Inspect the Private relay button from the email field.

**Expected result**
* The email field does't get stretched to the right side.

**Actual result**
* The email field gets expanded to the right side with a couple of pixels. 

**Additional notes**
* please observe the attached screenshot
![Screenshot from 2020-04-24 16-07-09](https://user-images.githubusercontent.com/43886441/80216874-6eec4780-8647-11ea-9e39-69a5cad15bc6.png)

**Comment by ksy36** [comment]
A similar issue is on https://account.habr.com 

<img width="705" alt="Screen Shot 2020-05-01 at 12 45 10 PM" src="https://user-images.githubusercontent.com/1303908/80822895-9f813380-8ba9-11ea-9494-aae036a34e0f.png">

**Comment by groovecoder** [comment]
This is fixed in my 1.3.1 add-on.

**Comment by sbadau** [comment]
I can confirm that the issue is no longer reproducible on https://account.habr.com with the latest version of the add-on and Firefox 77.0.1 (verified on Windows 10).

I'm still seeing the issue on Facebook's login form for the Create a Page, I left a comment in the #526 to cover this.
